{
 "title": "Share it!",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Technical Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "App Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "secure_storage_uptime_seconds" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "secure_storage_memory_usage_bytes",
     "legendFormat": "Memory Used"
    }
   ]
  },
  {
   "title": "HTTP Request Rate (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method, route) (rate(secure_storage_http_requests_total[5m]))",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "HTTP Average Response Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (method, route) (rate(secure_storage_http_request_duration_ms_sum[5m])) / sum by (method, route) (rate(secure_storage_http_request_duration_ms_count[5m]))",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "ThreadPool Threads Availability",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "secure_storage_threadpool_available_worker_threads",
     "legendFormat": "Available Worker Threads"
    },
    {
     "expr": "secure_storage_threadpool_available_iocp_threads",
     "legendFormat": "Available CompletionPort Threads"
    }
   ]
  },
  { "title": "Business Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Total Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "secure_storage_user_count" }
   ]
  },
  {
   "title": "Active Secrets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "secure_storage_active_secrets_count"
    }
   ]
  },
  {
   "title": "Config User Quota",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "secure_storage_config_quota_bytes"
    }
   ]
  },
  {
   "title": "Average Consumption/User",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "secure_storage_average_used_bytes"
    }
   ]
  },
  {
   "title": "Total Storage Consumed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "secure_storage_total_used_bytes"
    }
   ]
  },
  {
   "title": "Free Storage Quota Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "secure_storage_free_quota_percent",
     "legendFormat": "p{{percentile}} free quota"
    }
   ]
  },
  {
   "title": "System Allocated Quota vs Used Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "secure_storage_total_quota_bytes",
     "legendFormat": "Total Allocated Quota Limit"
    },
    {
     "expr": "secure_storage_total_used_bytes",
     "legendFormat": "Total Storage Space Consumed"
    }
   ]
  }
 ]
}